
Natural Language Processing -- Amazon dataset

In [ ]:
# importing depandencies
import nltk
import re
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Downloading stopwords
nltk.download("stopwords")
nltk.download("punkt")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
# connect to drive
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
!ls /content/drive/MyDrive/Dataset

 AmazonReview.csv     'IMDB Dataset.csv'
 AnimalsData	      'Student Mental health.csv'
 Churn_Modelling.csv  'Student Mental health.gsheet'
 Fish.csv

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Dataset/AmazonReview.csv')

In [ ]:
# printing data
print("Data : ")
data.head()

Data :

                                              Review  Sentiment
0  Fast shipping but this product is very cheaply...          1
1  This case takes so long to ship and it's not e...          1
2  Good for not droids. Not good for iPhones. You...          1
3  The cable was not compatible between my macboo...          1
4  The case is nice but did not have a glow light...          1

In [ ]:
# Removing null values
data.dropna(axis=0, inplace=True)

In [ ]:
# Dividing target and feature column
x = data['Review']
y = data['Sentiment']

In [ ]:
x

0        Fast shipping but this product is very cheaply...
1        This case takes so long to ship and it's not e...
2        Good for not droids. Not good for iPhones. You...
3        The cable was not compatible between my macboo...
4        The case is nice but did not have a glow light...
                               ...
24995    These cables (lightning) are far superior to m...
24996    This unit performs exactly as advertised.  I u...
24997    I had the key cut at a local hardware store cu...
24998    I love my case I ordered from amazon. It wasn'...
24999    Awsome!!! I loved this little speaker. It has ...
Name: Review, Length: 24999, dtype: object

In [ ]:
y

0        1
1        1
2        1
3        1
4        1
        ..
24995    5
24996    5
24997    5
24998    5
24999    5
Name: Sentiment, Length: 24999, dtype: int64

In [ ]:
# Sentence Tokenization
sent_tok = x.apply(lambda para: sent_tokenize(para, language="english"))
print("\nSentance Tokenization")
print(sent_tok)

Sentance Tokenization
0        [Fast shipping but this product is very cheapl...
1        [This case takes so long to ship and it's not ...
2        [Good for not droids., Not good for iPhones., ...
3        [The cable was not compatible between my macbo...
4        [The case is nice but did not have a glow ligh...
                               ...
24995    [These cables (lightning) are far superior to ...
24996    [This unit performs exactly as advertised., I ...
24997    [I had the key cut at a local hardware store c...
24998    [I love my case I ordered from amazon., It was...
24999    [Awsome!!!, I loved this little speaker., It h...
Name: Review, Length: 24999, dtype: object

In [ ]:
# Word Tokenization
word_tok = x.apply(lambda para: word_tokenize(para, language="english"))
print("\nWord Tokenization")
print(word_tok)

Word Tokenization
0        [Fast, shipping, but, this, product, is, very,...
1        [This, case, takes, so, long, to, ship, and, i...
2        [Good, for, not, droids, ., Not, good, for, iP...
3        [The, cable, was, not, compatible, between, my...
4        [The, case, is, nice, but, did, not, have, a, ...
                               ...
24995    [These, cables, (, lightning, ), are, far, sup...
24996    [This, unit, performs, exactly, as, advertised...
24997    [I, had, the, key, cut, at, a, local, hardware...
24998    [I, love, my, case, I, ordered, from, amazon, ...
24999    [Awsome, !, !, !, I, loved, this, little, spea...
Name: Review, Length: 24999, dtype: object

In [ ]:
# special symbols removal
x = x.apply(lambda elem: re.sub(r"[^a-zA-Z0-9]", " ", elem.lower()))
x

0        fast shipping but this product is very cheaply...
1        this case takes so long to ship and it s not e...
2        good for not droids  not good for iphones  you...
3        the cable was not compatible between my macboo...
4        the case is nice but did not have a glow light...
                               ...
24995    these cables  lightning  are far superior to m...
24996    this unit performs exactly as advertised   i u...
24997    i had the key cut at a local hardware store cu...
24998    i love my case i ordered from amazon  it wasn ...
24999    awsome    i loved this little speaker  it has ...
Name: Review, Length: 24999, dtype: object

In [ ]:
# Stopwords List
stopwords_list = stopwords.words("english")


# print("\nStop-words : ")
print(stopwords_list)
print("Total Stop Words in corpus : ",len(stopwords_list))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
Total Stop Words in corpus :  179

In [ ]:
def stopWordsRemoval(sentance):
    new_x_sentance = [' '.join([word for word in sentance.split() if not word in stopwords_list])]
    return new_x_sentance


# Removal of Stopwords
x = x.apply(lambda para: stopWordsRemoval(para))
x

0        [fast shipping product cheaply made brought gr...
1               [case takes long ship even worth dont buy]
2        [good droids good iphones cannot use features ...
3        [cable compatible macbook iphone also connecto...
4        [case nice glow light disappointed product mee...
                               ...
24995    [cables lightning far superior cables market e...
24996    [unit performs exactly advertised use climbing...
24997    [key cut local hardware store cut free program...
24998    [love case ordered amazon color looked online ...
24999    [awsome loved little speaker great sound super...
Name: Review, Length: 24999, dtype: object

In [ ]:
# For Lemmatizing
word_lama = WordNetLemmatizer()

# Stemmed Data
def wordLematize(sentance):
    lematized_data = [' '.join([word_lama.lemmatize(word) for word in sentance[0].split()])]
    return lematized_data

# lametizing
x = x.apply(lambda para: wordLematize(para)[0])
x

0        fast shipping product cheaply made brought gra...
1                  case take long ship even worth dont buy
2        good droids good iphones cannot use feature wa...
3        cable compatible macbook iphone also connector...
4        case nice glow light disappointed product meet...
                               ...
24995    cable lightning far superior cable market even...
24996    unit performs exactly advertised use climbing ...
24997    key cut local hardware store cut free programm...
24998    love case ordered amazon color looked online f...
24999    awsome loved little speaker great sound super ...
Name: Review, Length: 24999, dtype: object

In [ ]:
# # For Stemming
# word_stem = PorterStemmer()

# # Stemmed Data
# def wordStem(sentance):
#   stemed_data = [' '.join([word_stem.stem(word) for word in sentance[0].split()])]
#   return stemed_data

# # stemming
# x = x.apply(lambda para: wordStem(para))

In [ ]:
# Train-test split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.20)

In [ ]:
# Applying Count Vectorize
# (Bag of Words)
dictonary_Words_bow = CountVectorizer()
bow_x = dictonary_Words_bow.fit_transform(xtrain).toarray()
bow_y = dictonary_Words_bow.transform(xtest).toarray()

In [ ]:
bow_x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
bow_y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# Features
print("\nFeatures : ")
pd.DataFrame(dictonary_Words_bow.get_feature_names_out())

Features :

            0
0          00
1         000
2      000540
3      000mah
4      000mph
...       ...
22491   zwave
22492  zx1000
22493     zx2
22494   zx400
22495   zyxel

[22496 rows x 1 columns]

In [ ]:
# Printing the value of X
print("\nX(Using Count Vectorizer) : ")
print(bow_x)

X(Using Count Vectorizer) :
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
pd.DataFrame(bow_x)

,0,1,2,3,4,5,6,7,8,9,...,22486,22487,22488,22489,22490,22491,22492,22493,22494,22495
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Applying Tfidf Vectorizer (Tfidf Approach)
dictonary_Words_tfidf = TfidfVectorizer(stop_words="english", max_features=10000)
tfidf_x = dictonary_Words_tfidf.fit_transform(xtrain).toarray()

In [ ]:
tfidf_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
print("\nFeatures : ")
print(dictonary_Words_tfidf.get_feature_names_out())

Features :
['00' '000' '002' ... 'zunes' 'zx2' 'zx400']

In [ ]:
# Printing the value of X
print("\nX(Using TF-IDF Vectorizer) : ")
print(tfidf_x)

X(Using TF-IDF Vectorizer) :
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [ ]:
import numpy as np
print(np.array(tfidf_x[0]))

[0. 0. 0. ... 0. 0. 0.]

In [ ]:
# training the model
MB = MultinomialNB()
MB.fit(bow_x, ytrain)

MultinomialNB()

In [ ]:
# predicting test values
print("The Predicted Values of Y : ")
ypred = MB.predict(bow_y)
print(ypred)

The Predicted Values of Y :
[5 1 4 ... 4 2 4]

In [ ]:
# Accuracy Score
print("\nAccuracy Score", accuracy_score(ytest, ypred)*100)

Accuracy Score 44.76

In [ ]:
# Classification Report
print("Classification Report")
print(classification_report(y_true=ytest, y_pred=ypred))

Classification Report
              precision    recall  f1-score   support

           1       0.54      0.60      0.57       986
           2       0.37      0.35      0.36       999
           3       0.34      0.24      0.28       987
           4       0.37      0.46      0.41       979
           5       0.59      0.57      0.58      1049

    accuracy                           0.45      5000
   macro avg       0.44      0.45      0.44      5000
weighted avg       0.44      0.45      0.44      5000

In [ ]:
# training the model
rfc = RandomForestClassifier()
rfc.fit(bow_x, ytrain)

RandomForestClassifier()

In [ ]:
# predicting test values
print("The Predicted Values of Y : ")
ypred = rfc.predict(bow_y)
print(ypred)

The Predicted Values of Y :
[5 1 4 ... 3 2 4]

In [ ]:
# Accuracy Score
print("\nAccuracy Score", accuracy_score(ytest, ypred)*100)

Accuracy Score 44.72

In [ ]:
# Classification Report
print("Classification Report")
print(classification_report(y_true=ytest, y_pred=ypred))

Classification Report
              precision    recall  f1-score   support

           1       0.51      0.68      0.58       986
           2       0.36      0.24      0.29       999
           3       0.40      0.33      0.36       987
           4       0.37      0.37      0.37       979
           5       0.53      0.61      0.57      1049

    accuracy                           0.45      5000
   macro avg       0.43      0.45      0.43      5000
weighted avg       0.43      0.45      0.43      5000

In [ ]:
# training the model
dtc = DecisionTreeClassifier()
dtc.fit(bow_x, ytrain)

In [ ]:
# predicting test values
print("The Predicted Values of Y : ")
ypred = dtc.predict(bow_y)
print(ypred)

In [ ]:
# Accuracy Score
print("\nAccuracy Score", accuracy_score(ytest, ypred)*100)

In [ ]:
# Classification Report
print("Classification Report")
print(classification_report(y_true=ytest, y_pred=ypred))

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
ann = Sequential()
ann.add(Dense(units=16,activation="relu",input_dim=1))
ann.add(Dense(units=8,activation="relu"))
ann.add(Dense(units=5,activation="softmax"))

In [ ]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 16)                32

 dense_1 (Dense)             (None, 8)                 136

 dense_2 (Dense)             (None, 5)                 45

=================================================================
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compiling ANN
ann.compile(optimizer="adam",loss="crossentropy",metrics=['accuracy'])

In [ ]:
history=ann.fit(tfidf_x,ytrain,batch_size=32,epochs = 50)

Epoch 1/50

ValueError: ignored